/**
 * Fixture data for the masi pages, shared by the unit tests (through testUtils) and the layout test (layout/),
 * which runs in Node without a DOM: plain data only, nothing that imports a test library.
 */
export const job = {
  id: 7,
  title: 'Senior Java Developer',
  companyId: 3,
  companyName: 'Nortal AS',
  location: 'Tallinn',
  remote: 'HYBRID',
  salaryMin: null,
  salaryMax: null,
  status: 'OPEN' as const,
  firstSeenAt: '2026-09-18T08:00:00Z',
  lastSeenAt: '2026-09-18T09:00:00Z',
  closedAt: null,
  reopenedCount: 0,
  userNote: null,
  descriptionText: 'We are hiring. token-POSTING',
  matchScore: null,
  match: null,
  listings: [
    {
      id: 1,
      sourceId: 2,
      sourceKey: 'cvee',
      url: 'https://cv.ee/x',
      titleRaw: 'Senior Java Developer',
      companyRaw: 'Nortal',
      postedAt: '2026-09-17T00:00:00Z',
      expiresAt: null,
      firstSeenAt: '2026-09-18T08:00:00Z',
      lastSeenAt: '2026-09-18T09:00:00Z',
      missCount: 0,
      closedAt: null,
    },
  ],
  sources: ['cvee'],
  mergedIntoId: null,
  becameId: null,
  packageId: null,
  packageStatus: null,
};

export const prepared = {
  id: 11,
  jobId: 7,
  jobTitle: 'Senior Java Developer',
  companyName: 'Nortal AS',
  cvVersionId: 1,
  cvVersion: 2,
  language: null,
  tunedFromVersion: 2,
  writtenIn: 'en',
  status: 'PREPARED',
  attempts: 1,
  tunedCv: {
    summary: 'Fits the order-API role.',
    title: 'Senior Java Developer',
    roles: [
      {
        company: 'Tõrva Fintech OÜ',
        title: 'Senior Backend Engineer',
        collapsed: false,
        bullets: [{ achievementIndex: 0, text: 'Cut p99 latency from 800 ms to 120 ms' }],
      },
      {
        company: 'Riigi Infosüsteemide Amet',
        title: 'Software Developer',
        collapsed: true,
        bullets: [],
      },
    ],
    skills: ['Java', 'Kafka'],
    coverLetter: 'Dear Nortal team, token-LETTER',
  },
  coverLetter: 'Dear Nortal team, token-LETTER',
  claims: [],
  lint: [{ rule: 'keyword', detail: "the master supports 'Kafka' but the output never says it" }],
  model: 'claude-opus-5',
  costUsd: 0.12,
  error: null,
  userNotes: null,
  appliedAt: null,
  response: 'NONE',
  createdAt: '2026-09-18T09:00:00Z',
  updatedAt: '2026-09-18T09:05:00Z',
  artifacts: [
    {
      kind: 'CV_PDF' as const,
      contentType: 'application/pdf',
      size: 20000,
      sha256: 'ab',
      available: true,
    },
    {
      kind: 'LETTER_TXT' as const,
      contentType: 'text/plain',
      size: 400,
      sha256: 'cd',
      available: true,
    },
  ],
};
